### ISSUE TITLE
左击头像，有机会获得秒回chrome插件一枚

### ISSUE THREAD

**Issue by KnightJoker** [hanax/should-i-reply#1]
这个插件莫名的戳中笑点啊hhhhhhh
根本停不下来~

**Comment by hanax** [comment]
_(:з」∠)_ 笑个蛋啊！！！

**Comment by KnightJoker** [comment]
讲道理，你还不如写一个你发消息，接受方就疯狂提醒的插件😂
从用户角度来说，这个属于一个伪需求
不过为啥这么多个小时过去了，我为什么还是没有停下来啊hhhhhhhh

**Comment by hanax** [comment]
怒close issue哼
